// RUBB2.h automatically generated by bin/add_new_algorithm.pl
// in Mon Oct  9 12:19:49 2017.

//
// RUBB2.h -- definition of the class "RUBB2".
//
//    This file is part of the featsel program
//    Copyright (C) 2016  Marcelo S. Reis
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef RUBB2_H_
#define RUBB2_H_

#include "../global.h"
#include "../Solver.h"
#include "../ElementSubset.h"
#include "../OBDDTree.h"
#include "../ROBDD.h"


class RUBB2 : public Solver
{

private:

  // Stores the OBDDTree used to walk through the search space
  // 
  OBDDTree * obdd_tree;

  // Stores the search space restrictions
  //
  OBDD * obdd;

public:

  // Default constructor.
  //
  RUBB2 ();

  // Default destructor.
  //
  virtual ~RUBB2 ();

  // Run the algorithm, getting up to 'max_size_of_minima_list' minima.
  //
  void get_minima_list (unsigned int);

};

#endif /* RUBB2_H_ */
